ca bd bd!
ca epo e /home/dandi/.config/nvim/lua/dandi/abbrev/typos.lua
ca fdin find
ca fidn find
ca lazy Lazy
ca lsit list
ca lspinfo Lspinfo
ca man Man
ca mason Mason
ca n norm
ca q q!
ca t term
ia 3secon second
ia abbrevieate abbreviate
ia abobve above
ia abou about
ia abraham Abraham
ia abslute absolute
ia accepth accept
ia acces access
ia accesbility accessibility
ia accesibility accessibility
ia accesiblity accessibility
ia accesing accessing
ia accetntuate accentuate
ia accetp accept
ia accidently accidentally
ia accomodat accommodate
ia accoutn account
ia accronym acronym
ia accros across
ia acdounts accounts
ia acess access
ia acess acess
ia acpi ACPI
ia acrual actual
ia actualy actually
ia adadnya adanya
ia adala adalah
ia addr3ess address
ia addres address
ia adeueduct aqueduct
ia adfantages advantages
ia administor administer
ia adn and
ia adnroid android
ia adress address
ia advantagge advantage
ia ae are
ia aempty empty
ia aer are
ia afater after
ia affectionaly affectionaly
ia aftern after
ia agge age
ia aggresively aggressively
ia agian again
ia ahd add
ia ahs has
ia aht that
ia ahve have
ia ai I
ia ake take
ia aksk ask
ia akunbarudanzor unburdens
ia aliasses aliases
ia allah Allah
ia allah Allah SWT
ia alliaxe Allliance
ia allign align
ia alll all
ia allwah Allah
ia alnalyze analyze
ia alocate allocate
ia aloso also
ia alse also
ia alternatvies alternatives
ia altoogether altogether
ia alwasy always
ia alwsys always
ia alwyas always
ia amaka maka
ia amattresses mattresses
ia amenalbe amenable
ia america America
ia amil mail
ia amon among
ia amreicans Americans
ia amtrix matrix
ia anceient ancient
ia andn and
ia android Android
ia ane and
ia anhy any
ia animamte animate
ia anoteher another
ia anothere another
ia anoying annoying
ia ansd and
ia ansi ANSI
ia answre answer
ia antio nation
ia anythign anything
ia anyting anything
ia anywhre anywhere
ia aournd around
ia apache Apache
ia apaplication application
ia apend append
ia apera appear
ia aperthei apartheid
ia apge page
ia api API
ia apis APIs
ia aply apply
ia apperantly apparently
ia apperars appears
ia applicatoin application
ia apreciated appreciated
ia aprop prop
ia apsp apps
ia arabic Arabic
ia ar are
ia aratio ratio
ia aray array
ia archeology archaeology
ia archieve achieve
ia arent aren't
ia areound around
ia arethmatic arithmetic
ia arguent argument
ia argumaet argument
ia argumant argument
ia argumenet argument
ia argumetn argument
ia argumets arguments
ia aristotles Aristotle's
ia aroud around
ia aroung around
ia arros arrows
ia arsterisk asterisk
ia articel article
ia ascii ASCII
ia asean ASEAN 
ia ashemed ashamed
ia asigned assigned
ia asmaller smaller
ia assembyl assembly
ia Assgnment Assignment
ia assyra Assyria
ia assyria Assyria
ia Asychronous Asynchronous
ia ataou atau
ia atchitecture architecture
ia atributte attribute
ia atrtributes attributes
ia attribure attribute
ia attriburte attribute
ia attriubures attributes
ia attriubute attribute
ia atuo atau
ia aur AUR
ia australia Australia
ia autohr author
ia automaticaly automatically
ia autoryti authority
ia aututst august
ia availabel available
ia avalilabel available
ia avariables variables
ia avim Vim
ia avodi avoid
ia avter after
ia awater water
ia ayre are
ia bacanya bapanya
ia bacany bacanya
ia backgorund background
ia backgroudn background
ia backpsace backspace
ia backto back to
ia badnwith bandwidth
ia bahea bahwa
ia bandwith bandwidth
ia bashic basic
ia basichs basics
ia bationg bathing
ia batt4ery battery
ia becasue because
ia bechmarking benchmarking
ia becoem become
ia becuase because
ia beegitu begitu
ia befoer before
ia befor before
ia begginer beginner
ia begginsers beginners
ia beginer beginner
ia beginers beginners
ia begining beginning
ia beigin begin
ia beiing being
ia beleiefes belief's
ia belive believe
ia benefeits benefits
ia beradasarkan berdasarkan
ia berkutat berkarat
ia berperngaruh berpengaruh
ia beter better
ia betwee between
ia betweeen between
ia betwoeen between
ia beyon beyond
ia bi be
ia bidies bodies
ia binari binary
ia binayr binary
ia blaack black
ia bleow below
ia blinnk blink
ia bluetooth Bluetooth
ia bnefits benefits
ia bnen been
ia bolld bold
ia boolean Boolean
ia borneo Borneo
ia botom bottom
ia brancd brand
ia breezeless breeze less
ia breifly briefly
ia breitish British
ia briatain Britain
ia british British
ia brittel brittle
ia broser browser
ia brougth brought
ia bruinei Brunei
ia brwowser browser
ia bsd BSD
ia bubling bubbling
ia buddhism Buddhism
ia builign building
ia builtins builtin
ia buitl built
ia buitlin builtin
ia bulding building
ia buttton button
ia bweteen between
ia caceh cache
ia calbacks callbacks
ia calcultor calculator
ia cange change
ia cannonical canonical
ia canonot cannot
ia cant can't
ia caoused caused
ia capitaal capital
ia carret caret
ia carrieage carriage
ia catalouger cataloger
ia catanya caranya
ia catd card
ia categorrized categorized
ia catt call
ia centrury century
ia cereate create
ia chabge change
ia chabne change
ia chage change
ia chagen change
ia chagne change
ia chaneg change
ia changeing changing
ia charachter character
ia charactermode character mode
ia characther character
ia chareacter character
ia chatch catch
ia chatgpt ChatGPT
ia cheebkbond cheekbone
ia chekc check
ia china China
ia chinas China
ia chinas China's
ia chinese Chinese
ia chnage change
ia chnages changes
ia chnanged changed
ia chooisng choosing
ia chooose choose
ia choosen chosen
ia cintainer container
ia cirle circle
ia citty city
ia civiliation civilization
ia ckey key
ia classcified classified
ia cleaniess cleanness
ia cleansliness cleanliness
ia clebber clobber
ia clicke click
ia cli CLI
ia cliking clicking
ia clipboeard clipboard
ia cloesed closed
ia closign closing
ia clossest closest
ia cna can
ia cnn CNN
ia cntain contain
ia cntainer container
ia cofnlict conflict
ia cojunt count
ia collectioin collection
ia collectiono collection
ia columnd column
ia colunm column
ia comamnd command
ia comand command
ia commadn command
ia comman command
ia commane command
ia commbination combination
ia commersial commercial
ia commited committed
ia commnad command
ia commnand command
ia commnd command
ia commnet comment
ia commnets comments
ia communincation communication
ia companty company
ia compasion compassion
ia compatibel compatible
ia completyely completely
ia complicance compliance
ia compnay company
ia componnet component
ia comprimising compromising
ia comproisign comprising
ia compteiiton competition
ia computre computer
ia comunicates communicates
ia comunity community
ia comunna communal
ia comuputer computer
ia conatain contain
ia conatainer container
ia concepth concept
ia concurency concurrency
ia condcept concept
ia conde code
ia conditinoal conditional
ia condventtions conventions
ia conecrion connection
ia conencted connected
ia conetent content
ia confert convert
ia confgiure configure
ia configruation configuration
ia configruraation configuration
ia configurain configuration
ia confilict conflict
ia conflic conflict
ia conformace conformance
ia conformant conform ant
ia confversion conversion
ia congainers containers
ia conifig config
ia connedctoin connection
ia conntent content
ia conrairner container
ia conrect connect
ia consciousnewss consciousness
ia consciouts conscious
ia consideresd considered
ia consita consist
ia consitent consistent
ia consoel console
ia consortioum consortium
ia constandt constandt
ia constandt constant
ia constartints constraints
ia constatnt constant
ia constractor constructor
ia consumates consummates
ia containder container
ia containerfs containers
ia containner container
ia containts contains
ia conteint content
ia contemporrary contemporary
ia conten content
ia contente content
ia contetn content
ia contians contains
ia continers containers
ia continoue continue
ia contiue continue
ia contnent content
ia contol control
ia conventiosn conventions
ia converson conversion
ia cooding coding
ia cookeis cookies
ia coomand command
ia cooose choose
ia copmuter computer
ia corresoponding corresponding
ia costatnt constant
ia costco Costco
ia cotnrol control
ia couldnt could't
ia coulnt count
ia countrey country
ia couse cause
ia coutnerh counters
ia coyp copy
ia cpacity capacity
ia cpu CPU
ia cr3eate create
ia creaet create
ia Crearte Create
ia creat create
ia createing creating
ia createor creator
ia creationof creation of
ia crestes creates
ia crete create
ia creteria criteria
ia croppiing cropping
ia csrf CSRF
ia css CSS
ia csv CSV
ia culter culture
ia cummand command
ia curen current
ia curent current
ia currenty currently
ia currnet current
ia curucial crucial
ia custoamizatios customization
ia custoers customers
ia custormer customer
ia cutlere culture
ia @ dandiyuan@proton.me
ia dangef danger
ia darkmde darkmode
ia databae database
ia debian Debian
ia decenmber December
ia decieded decided
ia declaraation declaration
ia declaratino declaration
ia declareed declared
ia decodde decode
ia deevlopers developers
ia defautl default
ia deffault default
ia defices devices
ia defived derived
ia degre degree
ia dekstop desktop
ia delcared declared
ia delimit4r delimiter
ia delimitery delimiters
ia delte delete
ia democaracy democracy
ia democraicees democracies
ia denagan dengan
ia dependedn depended
ia descendatn descendant
ia descentants descendants
ia descriibe describe
ia descriptsionn description
ia descripttive descriptive
ia descrptor descriptor
ia desing design
ia desktop Desktop
ia despeickle despickle
ia detais detail
ia detectt detect
ia determina determine
ia de the
ia devault default
ia devce device
ia develeopment development
ia developd developed
ia developmen development
ia devices device's
ia devidces devices
ia dhcp DHCP
ia dibilanng dibilang
ia didnt didn't
ia diea idea
ia diference difference
ia differece difference
ia differecne difference
ia Differecne Difference
ia differenche difference
ia differencitates differentiates
ia differents different
ia differnt different
ia difficutl difficult
ia diguui digurui
ia dikalim diklaim
ia dimasksud dimaksud
ia dimaspradana4478 disappearance
ia dinnder dinner
ia diplay display
ia dipslay display
ia dipslaying displaying
ia dipute depute
ia direactory directory
ia direcory directory
ia direcotry directory
ia direcrory directory
ia direcrtory directory
ia directlye directly
ia directoru Directory
ia directory Directory
ia directoryies directories
ia directoyr directory
ia directy directly
ia directyly directly
ia disj disc
ia dissapeear disappear
ia distictive distinctive
ia distor distro
ia distrubution distribution
ia ditergarai diperbarui
ia divverent different
ia djacent adjacent
ia django Django
ia dleimiters delimiters
ia dns DNS
ia documen document
ia documetary documentary
ia documment document
ia documnet document
ia dodnt didn't
ia doesnt doesn't
ia Doesnt doesn't
ia doi do I
ia dom DOM
ia dont don't
ia donw down
ia donwload download
ia dosplay display
ia doucument document
ia dpeak speak
ia dpends depends
ia dring drink
ia drivefrs drivers
ia driveing driving
ia dsign design
ia dta data
ia dtatbases databases
ia dtat data
ia ducth duct
ia dul 2>/dev/null
ia dumsp dumps
ia durin during
ia dut due
ia duthch dutch
ia dvice device
ia dvices devices
ia dw3m w3m
ia dwonlaod download
ia dwonload download
ia dynamiclly dynamically
ia earclier earlier
ia earlisest earliest
ia earss ears
ia easeier easier
ia easyly easily
ia eatch each
ia eb be
ia eclare declare
ia ecleoses encloses
ia ecmascirpt ECMAScript
ia ecncoded encoded
ia ecoh echo
ia ecossystem ecosystem
ia edesigned designed
ia edifference difference
ia ediging editing
ia ediotr editor
ia editign editing
ia editro editor
ia editror editor
ia efect effect
ia effecgt effect
ia effetctiev effective
ia ehave have
ia eho who
ia ehte the
ia eht the
ia eill will
ia electoronic electronic
ia eleemnt element
ia eleents elements
ia elelment element
ia elemenet element
ia elemnt element
ia elemnts elements
ia elemtn element
ia eliptical elliptical
ia elmeent element
ia elment element
ia emacs Emacs
ia emebeded embedded
ia emost most
ia emphaise emphasis
ia emulateor emulator
ia enalbes enables
ia enalble enable
ia encapsulete encapsulate
ia ener enter
ia enginering engineering
ia english English
ia enterprize enterprise
ia entier entire
ia entireley entirely
ia entrie entire
ia env ENV
ia envireonment environment
ia environmen environment
ia environmet environment
ia envv Environment Variables
ia epalace palace
ia eps EPS
ia equivlents equivalents
ia eror error
ia es6 ES6
ia escapt escape
ia escreen screen
ia esential essential
ia esitimator estimator
ia espanssions expansions
ia estring string
ia etherenet Ethernet
ia ethernet Ethernet
ia eth the
ia eurasia Eurasia
ia europ Europe
ia euser user
ia eveent event
ia eveery every
ia eveerywhere everywhere
ia evefry every
ia evenet event
ia evertyhong everything
ia Everythins Everything
ia everyting everything
ia evetn event
ia evicde device
ia evnent event
ia excelent excellent
ia excepth except
ia excetp except
ia exchagne exchagne
ia exchagne exchange
ia exchgen exchange
ia executbale executable
ia exif EXIF
ia exixting existing
ia exmple example
ia expansoion expansion
ia experieced experienced
ia explicityly explicitly
ia expresion expression
ia expressino expression
ia expresssions expressions
ia exteremely extremely
ia extesnsion extension
ia exuals equals
ia fafourige favorite
ia fainth faith
ia falues values
ia falue value
ia fascimile facsimile
ia federationf federation
ia femoved removed
ia feture future
ia ffom from
ia fiatures features
ia fideos videos
ia fideo video
ia fidn find
ia fiedl field
ia fiel fail
ia fiel file
ia fielsd fields
ia fiels files
ia fierwalls firewalls
ia fiewer viewer
ia fiirst first
ia filell file ll
ia fileter filter
ia fil file
ia filnally finally
ia filse files
ia filsystem filesystem
ia filterign filtering
ia fime time
ia fim vim
ia finallly finally
ia finaly finally
ia finnish finish
ia firefox Firefox
ia firest first
ia firewalll firewall
ia firtual virtual
ia flatpack flatpak
ia fle file
ia fles files
ia flie file
ia folloiwng following
ia fomrat format
ia fo of
ia foollow follow
ia formater formater
ia fornt front
ia fot for
ia fotns fonts
ia fots fonts
ia fromat format
ia frou from
ia fucntino function
ia fucntion function
ia fullscreen Fullscreen
ia funcamgental fundamental
ia funcrion function
ia functino function
ia functinos functions
ia function Function
ia functionnality functionality
ia functiono function
ia furdamentals fundamentals
ia furnitrue furniture
ia futere future
ia fwiw for what it's worth
ia gabe gave
ia gactory factory
ia gelongs belongs
ia genearate generate
ia generaly generally
ia generatio generation
ia generatro generator
ia genereates generates
ia genra genera
ia genvironment environment
ia gerbawah terbawah
ia gerp grep
ia getags jags
ia ghath that
ia ghe the
ia gihtub GitHub
ia gihtyb GitHub
ia git Git
ia github GitHub
ia githyub GitHub
ia glboal global
ia gloabaly globally
ia gloave glove
ia globa global
ia Globbing Globing
ia globbla global
ia globla global
ia gneral general
ia gnerator generator
ia gnome GNOME
ia gnu GNU
ia goies goes
ia golang Golang
ia googd good
ia googel google
ia goto go-to
ia gous goes
ia governorate governor ate
ia gpl GPL
ia gplv2 GPLv2
ia gplv3 GPLv3
ia gpu GPU
ia gradinet gradient
ia granpda grandpa
ia graphicl graphical
ia greek Greek
ia greeks Greeks
ia groeup group
ia groudn ground
ia grousp group
ia grpe grep
ia grumpt grumpy
ia gruping grouping
ia gsettings gettings
ia gui GUI
ia guis GUIs
ia gutorial tutorial
ia gutys guys
ia hading hating
ia hakers hackers
ia hallowoin hallowing
ia handel Handel
ia hans hand
ia happend happened
ia happends happens
ia happesns happens
ia hased hashed
ia hatumu hatimu
ia havae have
ia hdr ####################################################################
ia hdup hidup
ia headeer header
ia headign heading
ia hedign heeding
ia he He
ia hello Hello
ia helo Hello
ia helpd help
ia heres here's
ia herval herbal
ia hes he's
ia hhousehold household
ia hhow how
ia hiddenf hidden
ia hieararchy hierarchy
ia hifher higher
ia highter higher
ia hightlight highlight
ia hiliy hilir
ia hinduism Hinduism
ia hinga hingga
ia hins hints
ia hisotians historians
ia hisotry history
ia histor history
ia histroy history
ia hlep help
ia hoem home
ia hong Hong
ia hoook hook
ia horizontaly horizontally
ia hostr hosts
ia houdeholds households
ia houese house
ia houman human
ia how How
ia hree here
ia hsared shared
ia htahun tahun
ia htan than
ia htat that
ia hte the
ia hthe the
ia htis this
ia hugo Hugo
ia hundresds hundreds
ia hust just
ia hwatis whatis
ia hwat what
ia hwere where
ia hwich which
ia hwihc which
ia hwo how
ia Hwo How
ia hwy why
ia hygine hygiene
ia iach each
ia iamages images
ia iamge image
ia iam I am
ia icmp ICMP
ia identihfy identify
ia identitty identity
ia idesa ideas
ia idnetical identical
ia idnonesia Indonesia
ia ifferent different
ia ifles files
ia ifno info
ia ifnormatin information
ia ifnormation information
ia iformation formation
ia ightness lightness
ia i I
ia iinstall install
ia iircc if I remember correctly
ia iirc IIRC
ia iis is
    ia iiterate iterate
ia imags image
ia imamah Imamah
ia imge image
ia im I'm
ia immams imams
ia imortance importance
ia impertaive imperative
ia impies implies
ia Implici Implicit
ia implict implicit
ia impolementation implementation
ia impolies implies
ia imporoved improved
ia imporovements improvements
ia importan important
ia importatn important
ia imporve improve
ia improev improve
ia imune immune
ia inadvertnet inadvertent
ia inavetebly inevitably
ia inboun inbound
ia incetpion inception
ia includde include
ia includin including
ia incoporation incorporation
ia indentatino indentation
ia independdecne independence
ia independece independence
ia indesks indeks
ia indexign indexing
ia indidcte indicate
ia indifidual individual
ia indoeneasia Indonesia
ia indoenesian Indonesian
ia indoensia Indonesia
ia indoensians Indonesians
ia indoesias Indonesia's
ia indo Indonesia
ia indonesia Indonesia
ia indonesian Indonesian
ia indonesians Indonesians
ia indonesias Indonesia
ia indtation indentation
ia ineteesting interesting
ia infiite infinite
ia informatinfor information for
ia informatino information
ia infuential influential
ia ingformation information
ia ingle single
ia ingnore ignore
ia ingormation information
ia inidonesians Indonesians
ia injedctedd injected
ia inodonesia Indonesia
ia inoed inode
ia inoformation information
ia inot into
ia inovasinya inovasi nya
ia inromation information
ia insall install
ia insatall install
ia inser insert
ia inshell in shell
ia inslay inlay
ia insonesia Indonesia
ia instaead instead
ia instagram Instagram
ia instalation installation
ia installaiton installation
ia instanes instances
ia institued instituted
ia instlaled installed
ia insuficient insufficient
ia intepreter interpreter
ia interacet interact
ia interactie interactive
ia interactivce interactive
ia interactivfe interactive
ia interal internal
ia interenet internet
ia intergraition integration
ia intermitten intermittent
ia intermpereter interpreter
ia intermpretation interpretation
ia intet intent
ia intractive interactive
ia intrduced introduced
ia introductiono introduction
ia introuduce introduce
ia intsalation installation
ia involfe involve
ia invormation information
ia ip IP
ia ipp IPP
ia ipv4 IPv4
ia ipv6 IPv6
ia irc IRC
ia islam Islam
ia isn in
ia isnt isn't
ia istener listener
ia ist It's
ia isze size
ia iterm2 iTerm2
ia itesm items
ia it It
ia itll it'll
ia itmean it mean
ia itn in
ia itno into
ia its it's
ia ivnoke invoke
ia iwdely widely
ia iwll will
ia iwth with
ia jakarta Jakarta
ia jaopanese Japanese
ia japanaese Japanese
ia japanesee Japanese
ia japanese Japanese
ia japan Japan
ia japn japan
ia javascript JavaScript
ia jekyll Jekyll
ia jesus Jesus
ia jinja2 Jinja2
ia jkt Jakarta
ia josb jobs
ia jpeg JPEG
ia js JavaScript
ia json JSON
ia jsut just
ia judaism Judaism
ia jungel jungle
ia kapitanya kapita nya
ia kebuuthan kebutuhan
ia kerashya kerasnya
ia kindl kindle
ia kisd kids
ia knowledgte knowledge
ia knwon known
ia kong Kong
ia kusage usage
ia laik like
ia langeuage language
ia languae language
ia languange language
ia lanjupt lanjut
ia lan LAN
ia largaer larger
ia las last
ia lates latest
ia latesst latest
ia launchhed launched
ia lcoaly locally
ia leemnets elements
ia lein line
ia lelments elements
ia lements elements
ia lengthh length
ia lern learn
ia leter letter
ia lettter letter
ia levarage leverage
ia levell level
ia libreoffice LibreOffice
ia liead lead
ia liek like
ia liete lite
ia lightwieght lightweight
ia lik link
ia lincoln Lincoln
ia linee line
ia lineked linked
ia ling link
ia linivng lining
ia linkt link
ia lin line
ia linse lines
ia linux Linux
ia linxu Linux
ia liscences licenses
ia lishcense license
ia lisngint listing
ia listerners listeners
ia listneers listeners
ia liteasi literasi
ia literasin literasi
ia litlle little
ia litreasinya literasinnya
ia littel little
ia litteraly literally
ia locatae locate
ia locla local
ia logica logic
ia lognger longer
ia loocate locate
ia loook look
ia Lorem Loren
ia lornum exec curl -sSL "http://metaphorpsum.com/paragraphs/"<left>
ia lsitens listens
ia lsit list
ia lts LTS
ia lua Lua
ia lup for i in {1..}; do echo item $i.; done<esc>?}<cr>i
ia lvies lives
ia lwas law
ia maachine machine
ia maanager manager
ia machhine machine
ia machien machine
ia maek make
ia magter matter
ia mainpulation manipulation
ia maintaenance maintenance
ia maintaint maintains
ia maket make
ia malacca Malacca
ia malasyia Malaysia
ia malaya Malaya
ia malayisia Malaysia
ia malaysia Malaysia
ia malaysuia Malaysia
ia manaage manage
ia manaeger manager
ia manageement management
ia manchines machines
ia mangager manager
ia manger manager
ia manipulatyed manipulated
ia manipultation manipulation
ia manke make
ia markdonw Markdown
ia markdown Markdown
ia markdwon markdown
ia marksers markers
ia marsk marks
ia masyarakay masyarakat
ia matchies matches
ia materialzied materialized
ia mathch match
ia mattial martial
ia maximumm maximum
ia md5 MD5
ia mdns mDNS
ia meata meta
ia mee Dandi Yuan Aridianto
ia meemory memory
ia meiji Meiji
ia meke make
ia memeofry memory
ia memeorabel memorable
ia memeorh memory
ia memgbers members
ia memilikii memiliki
ia menaingful meaningful
ia mengadapi menghadapi
ia mengakiibatkan mengakibatkan
ia mengaktakan mengatakan
ia mentri menteri
ia messanger messenger
ia metirics metrics
ia mexican Mexican
ia mgh https://github.com/Yuandandi
ia microsoft Microsoft
ia midified modified
ia midle middle
ia milions millions
ia minght might
ia misstype mistype
ia moderyn modern
ia modivy modify
ia moed mode
ia moistoure moisture
ia moniotor monitor
ia monitr monitor
ia morining morning
ia mor more
ia mornign morning
ia moses Moses
ia moset most
ia mosue mouse
ia motorcyle motorcycle
ia movbile mobile
ia moveing moving
ia movile mobile
ia mozilla Mozilla
ia mroe more
ia mtatter matter
ia muhamad Muhammad
ia muhammads Muhammad's
ia muhamma Muhammad
ia multidimensionall multidimensional
ia multinationa multinational
ia multipel multiple
ia muroid muroid
ia muschles muscles
ia musilim Muslim
ia muslim Muslim
ia muslims Muslims
ia mux tmux
ia myaning meaning
ia na an
ia nad and
ia namd named
ia namesa names
ia nam name
ia nat NAT
ia natrual natural
ia navbigate navigate
ia naviagation navigation
ia nebara negara
ia necesary necessary
ia necessayr necessary
ia nections sections
ia ned need
ia negar negara
ia negitiaate negotiate
ia neovim NeoVim
ia nestsed nestled
ia netehrelands Netherlands
ia neter enter
ia netework network
ia netflix Netflix
ia netherlands Netherlands
ia nethernlands Netherlands
ia netive native
ia networkign networking
ia nevariously nefariously
ia newlinen newline
ia newwer newer
ia nmpa nmap
ia noah Noah
ia nodieis bodies
ia noew new
ia nokiaas Nokia's
ia nokia Nokia
ia nokias Nokia's
ia nolder older
ia nost most
ia notatino notation
ia notgherlands Netherlands
ia nothign nothing
ia nothig nothing
ia noth north
ia notivication notification
ia nott not
ia ntetwork network
ia nto not
ia nubmer number
ia nuemerical numerical
ia nuerous numerous
ia numbe number
ia numbmer number
ia numericc numeric
ia numer number
ia numverical numerical
ia numver number
ia nwme name
ia obbsessed obsessed
ia obvsessed obsessed
ia ocassionaly occasionally
ia occuiped occupied
ia occuraces occur aces
ia occureances occurrences
ia occurence occurrence
ia occurences occurrences
ia ocmmand command
ia ocntiue continue
ia ocpy copy
ia ocunt count
ia ocur occur
ia od do
ia oen one
ia oepn open
ia oera era
ia oetstat netstat
ia ofer over
ia ofirgins origins
ia ofr for
ia ofrmat format
ia ofthen often
ia ofther other
ia ogher other
ia ogten often
ia ohowever however
ia ohw how
ia oiptons options
ia ois is
    ia oit It
ia okey okay
ia omg OMG
ia omited omitted
ia onet one
ia onlhy only
ia ontly only
ia ont not
ia ont on
ia onwe one
ia oom OOM
ia oone one
ia openeing opening
ia opengl OpenGL
ia openssh OpenSSH
ia operaor operator
ia operatin operation
ia Opern Open
ia opernsource ope resource
ia oper open
ia opertor operator
ia optinal optional
ia optioin option
ia optionla optional
ia optiosn option
ia optoins options
ia optoon option
ia oraganization organization
ia ordure order
ia origis origin
ia orignial original
ia osi OSI
ia os OS
ia otehr other
ia oter other
ia oter otter
ia otgher other
ia othe other
ia otomatisa otomatis
ia otpions options
ia ot to
ia otu out
ia ouptut output
ia outpus output
ia overlaped overlapped
ia overlaping overlapping
ia overrrid override
ia ov of
ia ovverride override
ia ownd own
ia pacckage package
ia packgae package
ia packge package
ia packges packages
ia padnoc pandoc
ia paernt parent
ia pahases phases
ia paht path
ia pakcages packages
ia paneds panes
ia papaer paper
ia paragpah paragraph
ia paragrahp paragraph
ia paragrpah paragraph
ia paramaeter parameter
ia parametere parameters
ia parametes parameters
ia parenet parent
ia parrent parent
ia particualr particular
ia passowrd password
ia passsed passed
ia pbuh PBUH
ia pcakage package
ia pci PCI
ia pdf PDF
ia peacefullly peacefully
ia p_elemnet p_element
ia pembershian pembersihan
ia peninsuallar peninsular
ia penuat penguat
ia peower power
ia perforamance performance
ia performang performing
ia performatnce performance
ia peritn print
ia perku perlu
ia perl Perl
ia permisisons permissions
ia permisson permission
ia permorming performing
ia pernickety persnickety
ia perobagation propagation
ia perserivn preserving
ia perviw preview
ia phouysical physical
ia physicall physical
ia pid PID
ia piosts posts
ia pirnt print
ia pitfals pitfalls
ia plaftrom platform
ia platfrom platform
ia playabel playable
ia plititcal political
ia ploting plotting
ia png PNG
ia poeple people
ia poman podman
ia populationof population of
ia porcesses processes
ia porgramming programming
ia porgrams programs
ia porne prone
ia posix POSIX
ia possibel possible
ia possinle possible
ia possitive positive
ia postsripts postscripts
ia potrayed portrayed
ia powere powers
ia powerfull powerful
ia pracitices practices
ia preciding preceding
ia precisson precision
ia prefent prevent
ia prefereed preferred
ia preferrred preferred
ia prefious previous
ia prefreneces preferences
ia preinted printed
ia preious previous
ia premisions permissions
ia premissions permissions
ia preocedures procedures
ia preoceedure procedure
ia prepetrator perpetrator
ia presentaiton presentation
ia presing pressing
ia presonal personal
ia prespective prospective
ia prevenet prevent
ia preverable preferable
ia prevfer prefer
ia previdous previous
ia previeous previous
ia previewous previous
ia previleged privileged
ia previwous previous
ia prevneting preventing
ia prhase phrase
ia priciples principles
ia prifat private
ia pring print
ia prin preen
ia pritn print
ia privacey privacy
ia priveous previous
ia proceded proceeded
ia procedre procedure
ia procedurla procedural
ia proceudure procedure
ia procject project
ia proctechted protected
ia profide provide
ia PROFIEL PROFILE
ia profirt profit
ia progaming programming
ia programing programming
ia prominetn prominent
ia promram program
ia promtp prompt
ia properti property
ia prophtets prophets
ia propietary proprietary
ia propionents proponents
ia proprietayr proprietary
ia propterties properties
ia prormat format
ia prot port
ia prots ports
ia proviate private
ia prtray portray
ia pruposes purposes
ia pseed speed
ia ptogram program
ia ptorayed portrayed
ia publik public
ia purgint purging
ia puropose purpose
ia purpos purpose
ia qr QR
ia questeion question
ia quiestion question
ia quiotes quotes
ia quran Qur'an
ia radion radio
ia randonm random
ia randr RandR
ia rangkng rangking
ia rdf RDF
ia readlink read link
ia realy really
ia reassingde reassigned
ia reassingned reassigned
ia reature feature
ia recongnize recognize
ia recuresively recursively
ia recuresvely recursively
ia recurevel recuresively
ia recurseive recursive
ia redhat Redhat
ia redirectign redirecting
ia redner render
ia redundatn redundant
ia redundent redundant
ia reeally really
ia reeset reset
ia referrs refers
ia reguar regular
ia reidirect redirect
ia relatibve relative
ia relevatn relevant
ia relfect reflect
ia religiouse religious
ia religirons religions
ia reltaed related
ia remofe remove
ia removeing removing
ia remve remove
ia remvoed removed
ia remvoe remove
ia renadah rendah
ia renadh rendah
ia rendre render
ia renmae rename
ia repl real
ia repo rep
ia repositroy repository
ia requried required
ia requriemetns requirements
ia resasons reasons
ia resemblence resemblance
ia resons reasons
ia resutl result
ia retirn return
ia retirun return
ia rets rest
ia retturn return
ia reveald revealed
ia rever refer
ia righr right
ia rithtful rightful
ia rmeove remove
ia rmy my
ia roatate rotate
ia roder order
ia rooot root
ia ro or
ia rpint print
ia rss RSS
ia runing running
ia runique unique
ia ruude rude
ia saha saja
ia sape shape
ia sarawak Sarawak
ia saty say
ia savely safely
ia sbeds beds
ia scatered scattered
ia scipt sci pt
ia screan screen
ia screeen screen
ia scren screen
ia scrigpt script
ia scritp script
ia scrpt script
ia scultpture sculptures
ia scutlures cultures
ia searchsploti searchsploit 
ia searhch search
ia searhc search
ia sebagh sabah
ia seccure secure
ia secodns seconds
ia secrue secure
ia secureity security
ia secur recur
ia seeek seek
ia seee see
ia seeral several
ia seeseorang seseorang
ia semanics semantics
ia sensiteive sensitive
ia sensitibe sensitive
ia sentury century
ia seo SEO
ia sepace space
ia sepecies species
ia sepecifiecally specifically
ia september September
ia sequenncd sequenced
ia sequentiallly sequentially
ia sequentlly sequentially
ia serndir sendiri
ia serviece service
ia sesua sesuai
ia setptember september
ia sfelist safelist
ia shareing sharing
ia shart start
ia sha SHA
ia she She
ia shes she's
ia shoew show
ia shoppign shopping
ia shor show
ia shoudl should
ia shoulc should
ia shouldnt shouldn't
ia shouled should
ia showereing showering
ia showr show
ia shpo shop
ia shuch such
ia sice since
ia siet site
ia significat significant
ia signinficance significance
ia signinficantly significantly
ia si is
    ia sii see
ia siletn silent
ia simillar similar
ia simultaenously simultaneously
ia sinagaproe Singapore
ia singel single
ia sixze size
ia skilstak skilstak
ia slightliy slightly
ia slugggish sluggish
ia smalleer smaller
ia smoot smooth
ia socets sockets
ia soekarno Soekarno
ia soekarno Sukarno
ia soem some
ia softare software
ia softerwere software
ia softweare software
ia softwrae software
ia sohuth south
ia somehting something
ia somethign something
ia Somethig Something
ia somethimes sometimes
ia sometines sometimes
ia somtehing something
ia soources sources
ia soudns sounds
ia sould should
ia souncdard soundcard
ia sourcde sourced
ia SOURCEs SOURCES
ia sovereingty sovereignty
ia spearker speaker
ia speciallity specialty
ia speciall special
ia specidfic specific
ia specifed specified
ia specifes specifies
ia specifidc specific
ia specivic specific
ia spedning spending
ia speen spin
ia spirirual spiritual
ia splititng splitting
ia ssg SSG
ia sstem system
ia stablished established
ia stagging staging
ia standadr standard
ia starbucks Starbucks
ia starndard standard
ia startitng starting
ia stateement statement
ia statemenet statement
ia states States
ia staticaly statically
ia statmeent statement
ia statmenet statement
ia statment statement
ia statred started
ia statr start
ia steatlh stealth
ia sthe the
ia stil still
ia stirngs strings
ia stonesa stones
ia strenth strength
ia strint string
ia struff stuff
ia sttus status
ia styeles styles
ia styelsheet stylesheet
ia styel style
ia suati suatu
ia subtitutions substitutions
ia subtitution substitution
ia subystem subsystem
ia succesfully successfully
ia succesful successful
ia succesfuly successfully
ia succesor successor
ia sucdh such
ia suc such
ia suer user
ia sufficinet sufficient
ia sufix suffix
ia sugestions suggestions
ia sukarno Sukarno
ia superflosu superfluous
ia suppresed suppressed
ia surender surrender
ia suroundign surrounding
ia surprigisng surprising
ia suse use
ia sustioner sustainer
ia swhitch switch
ia swiss Swiss
ia swt SWT
ia sybmolic symbolic
ia sybsystem subsystem
ia symbolci symbols
ia symbos symbol
ia syntak syntax
ia sytyle style
ia taht that
ia taiwan Taiwan
ia takign taking
ia taks taks
ia tath that
ia tcp TCP
ia teahidng teaching
ia tehe the
ia teh the
ia televisio televisi
ia televisio television
ia teminal terminal
ia templeate template
ia temporayr temporary
ia termianal terminal
ia termianl terminal
ia terminall terminal
ia termingal terminal
ia terminla terminal
ia terml terms
ia termnal terminal
ia tesla Tesla
ia tghe the
ia tha that
ia thatn than
ia thats that's
ia thean than
ia theat that
ia theem them
ia theer there
ia thefaces the faces
ia theis this
ia theoir their
ia theree there
ia theres there's
ia theri their
ia therme there
ia ther their
ia thery there
ia thesse these
ia thes this
ia tHe tHe
ia thext text
ia theyre they're
ia they They
ia thhrough through
ia thidr third
ia thieeory theory
ia thiems times
ia thier their
ia thies this
ia thie the
ia thight tight
ia thigns things
ia thign thing
ia thingk think
ia thinnk think
ia Thisng Things
ia thi the
ia thorugh through
ia thoruth through
ia thoug though
ia thout thought
ia thpe type
ia throught thought
ia throug through
ia throut through
ia th the
ia tht that
ia thwo two
ia tiem time
ia tierminal terminal
ia tiktok TikTok
ia tithub GitHub
ia tlah telah
ia tls TLS
ia todah today
ia todo TODO
ia togetheh together
ia tomato 🍅
ia tommorow tomorrow
ia tonw town
ia tow two
ia tpee type
ia tracet traced
ia tradision tradition
ia traditioally traditionally
ia trafic traffic
ia transtitions transitions
ia trasdidiotnal traditional
ia travelt travel
ia traversla traversal
ia trea Tera
ia treminal terminal
ia treu true
ia tshirt T-Shirt
ia tty TTY
ia tui TUI
ia tursn turn
ia tu too
ia tyepes types
ia tyep type
ia typicalyy typically
ia ubuntu Ubuntu
ia ubutnu Ubuntu
ia udner under
ia udnoubtedly undoubtedly
ia udp UDP
ia uisngg using
ia umverella umbrella
ia uncacceptable unacceptable
ia Uncerstatnd Understand
ia underlaying underlying
ia underpinings underpinnings
ia undershore underscore
ia Understatnd Understand
ia undet under
ia uniquie unique
ia united United
ia unitued united
ia univesa unviersal
ia unix Unix
ia unladden unladen
ia unndouubtedly undoubtedly
ia unsuccesfully unsuccessfully
ia untik untuk
ia unveilled unveiled
ia unversally universally
ia unwnted unwanted
ia upercase uppercase
ia uphil uphill
ia upt up
ia urls URLs
ia url URL
ia ursers users
ia usb USB
ia usefull useful
ia useing using
ia usenames usernames
ia userd used
ia usign using
ia using Using
ia usin using
ia usite suite
ia usng using
ia usptream upstream
ia usses uses
ia ussuallly usually
ia usualy usually
ia ususally usually
ia utilitky utility
ia utilitye utility
ia utitility utility
ia vaibrale variable
ia vairable variable
ia valiues values
ia valu vale
ia variabel variable
ia varianle variable
ia variaous various
ia varibales variables
ia varius various
ia varuable variable
ia veing being
ia veiw view
ia verifid verified
ia verison version
ia versiaon version
ia versino version
ia version version
ia vfertical vertical
ia viatal vital
ia viddeo video
ia videous video's
ia vides videos
ia vidoe video
ia viles files
ia vim Vim
ia vinal final
ia virtua virtual
ia virtulan virtual
ia virtula virtual
ia vish fish
ia visisted visited
ia vitual virtual
ia vitual virtula
ia vlaues values
ia vlaue value
ia vlaus values
ia vlexible flexible
ia voacab vocab
ia vscode VSCode
ia vuitlin builtin
ia waht What
ia warnign warning
ia wasiting wasting
ia wasnt wasn't
ia wat3er water
ia watchign watching
ia watning wanting
ia watre water
ia wcho echo
ia weeki week
ia wehic which
ia wel well
ia wepage webpage
ia were we're
ia wetern western
ia wether whteher
ia whar what
ia whats what's
ia what What
ia wha what
ia whay why
ia whch which
ia whdy why
ia whenevder whenever
ia whenn when
ia when When
ia wher where
ia whidh which
ia whn when
ia whoch which
ia whree where
ia whre where
ia whsy why
ia whtn when
ia wht what
ia wich which
ia widht width
ia widnows windows
ia widonws windows
ia wigthin within
ia wiht with
ia willl will
ia wil will
ia windos windows
ia wiritten written
ia wirk work
ia withing within
ia withoiut without
ia wi whatis
ia wiwtah with
ia wiwth with
ia woerk work
ia wofk work
ia wokr work
ia wonce once
ia wonderyng wondering
ia wont won't
ia woudl would
ia wouldnt wouldn't
ia writiing writing
ia writting writing
ia wsl2 WSL2
ia wsl WSL
ia www WWW
ia wya way
ia wysiwyg what you see is what you get
ia wy why
ia xinjiang Xinjinag
ia xslt XSLT
ia yagn yang
ia yare year
ia yello yellow
ia yoou you
ia yoru your
ia youll you'll
ia youre you're
ia yours your's
ia yourube YouTube
ia yousing using
ia youtube YouTube
ia youu you
ia you You
ia yu you
ia zealand Zealand
ia albert Albert
ia einstein Einstein
ia aristoteles Aristotle's
ia benjamin Benjamin
ia franklin Franklin
ia confucius Confucius
ia steve Steve
ia zola Zola
