ca bd bd!
ca epo e /home/dandi/.config/nvim/lua/dandi/abbrev/typos.lua
ca fdin find
ca fidn find
ca lazy Lazy
ca lspinfo Lspinfo
ca man Man
ca mason Mason
ca q q!
ca t term
ia todo TODO
ia @ dandiyuan@proton.me
ia env ENV
ia envv Environment Variables
ia hello Hello
ia Crearte Create
ia Differecne Difference
ia Doesnt doesn't
ia Everythins Everything
ia Globbing Globing
ia Hwo How
ia Hwo How
ia Opern Open
ia SOURCEs SOURCES
ia Somethig Something
ia Uncerstatnd Understand
ia Understatnd Understand
ia abou about
ia accetp accept
ia accomodat accommodate
ia acdounts accounts
ia acess acess
ia actualy actually
ia adadnya adanya
ia adala adalah
ia addr3ess address
ia addres address
ia adeueduct aqueduct
ia adfantages advantages
ia administor administer
ia adn and
ia adnroid android
ia adress address
ia advantagge advantage
ia aftern after
ia agge age
ia aggresively aggressively
ia agian again
ia ahd add
ia aht that
ia ai I
ia ake take
ia aksk ask
ia allah Allah
ia allah Allah SWT
ia alliaxe Allliance
ia allwah Allah
ia alnalyze analyze
ia aloso also
ia alse also
ia alwsys always
ia amaka maka
ia amattresses mattresses
ia america America
ia amon among
ia amreicans Americans
ia anceient ancient
ia andn and
ia android Android
ia ane and
ia anoteher another
ia anothere another
ia anoying annoying
ia anoying annoying
ia antio nation
ia anythign anything
ia anyting anything
ia aournd around
ia apache Apache
ia apaplication application
ia apend append
ia applicatoin application
ia aprop prop
ia ar are
ia arabic Arabic
ia arent aren't
ia areound around
ia aristotles Aristotle's
ia aroud around
ia aroung around
ia arros arrows
ia arsterisk asterisk
ia articel article
ia asean ASEAN 
ia ashemed ashamed
ia asmaller smaller
ia ataou atau
ia atchitecture architecture
ia atuo atau
ia australia Australia
ia automaticaly automatically
ia autoryti authority
ia aututst august
ia availabel available
ia awater water
ia ayre are
ia bacany bacanya
ia bacanya bapanya
ia backgroudn background
ia badnwith bandwidth
ia bahea bahwa
ia bandwith bandwidth
ia bationg bathing
ia becoem become
ia beegitu begitu
ia begginsers beginners
ia beginers beginners
ia beigin begin
ia beiing being
ia beleiefes belief's
ia beradasarkan berdasarkan
ia berkutat berkarat
ia berperngaruh berpengaruh
ia betweeen between
ia betwoeen between
ia beyon beyond
ia bi be
ia bidies bodies
ia binari binary
ia bnen been
ia borneo Borneo
ia borneo Borneo
ia brancd brand
ia breitish British
ia briatain Britain
ia british British
ia broser browser
ia brougth brought
ia bruinei Brunei
ia buddhism Buddhism
ia builign building
ia builtins builtin
ia buitlin builtin
ia bulding building
ia ca Ca
ia calcultor calculator
ia cant can't
ia caoused caused
ia carrieage carriage
ia catanya caranya
ia centrury century
ia chabne change
ia chage change
ia chagen change
ia chagne change
ia charachter character
ia characther character
ia chatgpt ChatGPT
ia chatgpt ChatGPT
ia cheebkbond cheekbone
ia china China
ia chinas China
ia chinas China's
ia chinese Chinese
ia chnage change
ia chnanged changed
ia chooisng choosing
ia chooose choose
ia cintainer container
ia citty city
ia civiliation civilization
ia ckey key
ia classcified classified
ia cleaniess cleanness
ia cleansliness cleanliness
ia clebber clobber
ia cli CLI
ia cliking clicking
ia clipboeard clipboard
ia cna can
ia cnn CNN
ia cntainer container
ia cofnlict conflict
ia collectiono collection
ia columnd column
ia comamnd command
ia comand command
ia wi whatis
ia commadn command
ia commadn command
ia comman command
ia commbination combination
ia commersial commercial
ia commited committed
ia commnand command
ia companty company
ia compatibel compatible
ia compnay company
ia compnay company
ia comprimising compromising
ia comproisign comprising
ia compteiiton competition
ia computre computer
ia comunicates communicates
ia comunity community
ia comunna communal
ia comuputer computer
ia conatainer container
ia condcept concept
ia conde code
ia confgiure configure
ia configruraation configuration
ia configurain configuration
ia confilict conflict
ia congainers containers
ia connedctoin connection
ia conrairner container
ia conrect connect
ia conrect connect
ia consciousnewss consciousness
ia consciouts conscious
ia consideresd considered
ia consita consist
ia consitent consistent
ia consoel console
ia consortioum consortium
ia constartints constraints
ia consumates consummates
ia containder container
ia containerfs containers
ia contemporrary contemporary
ia contetn content
ia continers containers
ia contnent content
ia contol control
ia cookeis cookies
ia coomand command
ia cooose choose
ia copmuter computer
ia costco Costco
ia cotnrol control
ia couldnt could't
ia coulnt count
ia countrey country
ia couse cause
ia cpacity capacity
ia cpu CPU
ia cpu CPU
ia cpu CPU
ia creaet create
ia creationof creation of
ia creationof creation of
ia crestes creates
ia culter culture
ia curucial crucial
ia custoamizatios customization
ia cutlere culture
ia darkmde darkmode
ia de the
ia decenmber December
ia decieded decided
ia declareed declared
ia deevlopers developers
ia defautl default
ia deffault default
ia defived derived
ia dekstop desktop
ia delcared declared
ia democaracy democracy
ia democraicees democracies
ia denagan dengan
ia dependedn depended
ia descentants descendants
ia descrptor descriptor
ia detais detail
ia devault default
ia develeopment development
ia developd developed
ia developmen development
ia dhcp DHCP
ia didnt didn't
ia diea idea
ia differece difference
ia differecne difference
ia differenche difference
ia differencitates differentiates
ia differents different
ia difficutl difficult
ia diguui digurui
ia dikalim diklaim
ia dimasksud dimaksud
ia dipslaying displaying
ia dipute depute
ia direcory directory
ia direcrory directory
ia direcrtory directory
ia directory Directory
ia directoryies directories
ia directoyr directory
ia directyly directly
ia dissapeear disappear
ia distictive distinctive
ia distor distro
ia distrubution distribution
ia ditergarai diperbarui
ia divverent different
ia dns DNS
ia documetary documentary
ia doesnt doesn't
ia dont don't
ia dosplay display
ia dpeak speak
ia dring drink
ia driveing driving
ia driveing driving
ia dsign design
ia dta data
ia dtatbases databases
ia ducth duct
ia dut due
ia duthch dutch
ia duthch dutch
ia dvice device
ia dw3m w3m
ia earlisest earliest
ia earss ears
ia easeier easier
ia easyly easily
ia eb be
ia ecleoses encloses
ia ecncoded encoded
ia ecossystem ecosystem
ia edesigned designed
ia edifference difference
ia ediging editing
ia ediotr editor
ia editign editing
ia editror editor
ia effecgt effect
ia effetctiev effective
ia ehave have
ia eho who
ia eht the
ia eill will
ia electoronic electronic
ia electoronic electronic
ia emacs Emacs
ia emphaise emphasis
ia enalble enable
ia ener enter
ia english English
ia envireonment environment
ia environmen environment
ia epalace palace
ia equivlents equivalents
ia esitimator estimator
ia eth the
ia ethernet Ethernet
ia ethernet Ethernet
ia eurasia Eurasia
ia europ Europe
ia eveerywhere everywhere
ia evertyhong everything
ia excelent excellent
ia exchagne exchagne
ia exchagne exchange
ia exchgen exchange
ia executbale executable
ia exixting existing
ia exmple example
ia experieced experienced
ia expresion expression
ia fainth faith
ia federationf federation
ia femoved removed
ia fi if
ia fidn find
ia fiedl field
ia fiel fail
ia fiel file
ia fiels files
ia fierwalls firewalls
ia filell file ll
ia filnally finally
ia filse files
ia filsystem filesystem
ia filterign filtering
ia fim vim
ia finallly finally
ia finnish finish
ia finnish finish
ia firewalll firewall
ia firtual virtual
ia fle file
ia flie file
ia fo of
ia fornt front
ia fromat format
ia frou from
ia funcamgental fundamental
ia furdamentals fundamentals
ia furnitrue furniture
ia gabe gave
ia gactory factory
ia generaly generally
ia generatio generation
ia genra genera
ia genvironment environment
ia gerbawah terbawah
ia ghath that
ia ghe the
ia gihtyb GitHub
ia github GitHub
ia github GitHub
ia gloabaly globally
ia gloave glove
ia goies goes
ia googd good
ia goto go-to
ia governorate governor ate
ia gpu GPU
ia graphicl graphical
ia greek Greek
ia greeks Greeks
ia groeup group
ia groudn ground
ia grousp group
ia gta Grand Theft Auto
ia gui GUI
ia gutorial tutorial
ia gutys guys
ia hallowoin hallowing
ia hans hand
ia hatumu hatimu
ia hdr ####################################################################
ia hdup hidup
ia he He
ia helpd help
ia heres here's
ia hes he's
ia hhousehold household
ia hieararchy hierarchy
ia hightlight highlight
ia hiliy hilir
ia hinduism Hinduism
ia hinga hingga
ia hins hints
ia hisotians historians
ia hisotry history
ia histor history
ia hlep help
ia hoem home
ia hong Hong
ia houdeholds households
ia houese house
ia houman human
ia hree here
ia htahun tahun
ia htan than
ia htat that
ia hte the
ia htis this
ia hundresds hundreds
ia hwat what
ia hwo how
ia hygine hygiene
ia i I
ia iam I am
ia iamge image
ia id ID 
ia idesa ideas
ia idnonesia Indonesia
ia ifferent different
ia ifnormatin information
ia iinstall install
ia im I'm
ia imags image
ia imamah Imamah
ia imge image
ia immams imams
ia imortance importance
ia impolementation implementation
ia imporoved improved
ia imporovements improvements
ia importan important
ia importatn important
ia improev improve
ia includde include
ia includin including
ia incoporation incorporation
ia independdecne independence
ia independece independence
ia indesks indeks
ia indifidual individual
ia indo Indonesia
ia indoeneasia Indonesia
ia indoenesian Indonesian
ia indoensia Indonesia
ia indoensians Indonesians
ia indoesias Indonesia's
ia indonesia Indonesia
ia indonesia Indonesia
ia indonesian Indonesian
ia indonesians Indonesians
ia indonesias Indonesia
ia informatinfor information for
ia informatino information
ia infuential influential
ia ingnore ignore
ia ingormation information
ia inidonesians Indonesians
ia inodonesia Indonesia
ia inoed inode
ia inot into
ia inovasinya inovasi nya
ia insatall install
ia inslay inlay
ia insonesia Indonesia
ia instaead instead
ia installaiton installation
ia institued instituted
ia interacet interact
ia interal internal
ia interenet internet
ia intergraition integration
ia intermitten intermittent
ia intermpereter interpreter
ia intermpretation interpretation
ia introductiono introduction
ia introuduce introduce
ia intsalation installation
ia ip IP
ia ip IP
ia ip IP
ia ipp IPP
ia ipv4 IPv4
ia ipv6 IPv6
ia islam Islam
ia islam Islam
ia islam Islam
ia isn in
ia isnt isn't
ia it It
ia iterm2 iTerm2
ia itll it'll
ia itmean it mean
ia itn in
ia itno into
ia iwdely widely
ia jakarta Jakarta
ia jaopanese Japanese
ia japan Japan
ia japanaese Japanese
ia japanese Japanese
ia japanese Japanese
ia japanese Japanese
ia japanesee Japanese
ia japn japan
ia japn japan
ia javascript JavaScript
ia jesus Jesus
ia jkt Jakarta
ia js JavaScript
ia judaism Judaism
ia jungel jungle
ia kapitanya kapita nya
ia kebuuthan kebutuhan
ia kerashya kerasnya
ia kisd kids
ia kisd kids
ia knowledgte knowledge
ia knwon known
ia kong Kong
ia lan LAN
ia lanjupt lanjut
ia largaer larger
ia launchhed launched
ia liead lead
ia lightwieght lightweight
ia lineked linked
ia linivng lining
ia linux Linux
ia linxu Linux
ia lishcense license
ia liteasi literasi
ia literasin literasi
ia litreasinya literasinnya
ia locla local
ia logica logic
ia loook look
ia lorem ~/bin/lorem.sh
ia lua Lua
ia lup for i in {1..}; do echo item $i.; done<esc>?}<cr>i
ia lvies lives
ia lwas law
ia maanager manager
ia machhine machine
ia magter matter
ia maintaenance maintenance
ia maket make
ia malacca Malacca
ia malacca Malacca
ia malasyia Malaysia
ia malasyia Malaysia
ia malaya Malaya
ia malaya Malaya
ia malayisia Malaysia
ia malaysia Malaysia
ia malaysia Malaysia
ia malaysia Malaysia
ia malaysuia Malaysia
ia manaeger manager
ia manageement management
ia manchines machines
ia manger manager
ia markdonw Markdown
ia markdown Markdown
ia marksers markers
ia masyarakay masyarakat
ia materialzied materialized
ia mattial martial
ia mee Dandi Yuan Aridianto
ia meiji Meiji
ia memeofry memory
ia memeorabel memorable
ia memgbers members
ia memilikii memiliki
ia mengadapi menghadapi
ia mengakiibatkan mengakibatkan
ia mengaktakan mengatakan
ia mentri menteri
ia messanger messenger
ia mgh https://github.com/Yuandandi
ia microsoft Microsoft
ia midified modified
ia milions millions
ia minght might
ia moderyn modern
ia moniotor monitor
ia monitr monitor
ia mor more
ia morining morning
ia mornign morning
ia moses Moses
ia moset most
ia motorcyle motorcycle
ia moveing moving
ia movile mobile
ia mtatter matter
ia muhamad Muhammad
ia muhamma Muhammad
ia muhammads Muhammad's
ia multinationa multinational
ia muroid muroid
ia muschles muscles
ia musilim Muslim
ia muslim Muslim
ia muslim Muslim
ia muslim Muslim
ia muslims Muslims
ia mux tmux
ia namd named
ia namesa names
ia nat NAT
ia navbigate navigate
ia naviagation navigation
ia nebara negara
ia necessayr necessary
ia negar negara
ia neovim NeoVim
ia netehrelands Netherlands
ia neter enter
ia netflix Netflix
ia netherlands Netherlands
ia nethernlands Netherlands
ia netive native
ia networkign networking
ia nmpa nmap
ia noah Noah
ia nodieis bodies
ia nokia Nokia
ia nokia Nokia
ia nokia Nokia
ia nokia Nokia
ia nokia Nokia
ia nokia Nokia
ia nokiaas Nokia's
ia nokias Nokia's
ia nost most
ia notgherlands Netherlands
ia noth north
ia ntetwork network
ia nto not
ia nubmer number
ia nuerous numerous
ia nwme name
ia obbsessed obsessed
ia obvsessed obsessed
ia occuiped occupied
ia occurence occurrence
ia ocntiue continue
ia ocpy copy
ia od do
ia oera era
ia ofer over
ia ofirgins origins
ia ofr for
ia ofthen often
ia ofther other
ia ogher other
ia ogten often
ia ohowever however
ia ohw how
ia oit It
ia okey okay
ia onet one
ia ont on
ia onwe one
ia oone one
ia openeing opening
ia openssh OpenSSH
ia oper open
ia operatin operation
ia oraganization organization
ia origis origin
ia ot to
ia otehr other
ia oter other
ia oter otter
ia otgher other
ia othe other
ia otomatisa otomatis
ia ownd own
ia packges packages
ia pakcages packages
ia papaer paper
ia parrent parent
ia pbuh PBUH
ia pdf PDF
ia peacefullly peacefully
ia peninsuallar peninsular
ia penuat penguat
ia peower power
ia performang performing
ia peritn print
ia perku perlu
ia perl Perl
ia perl Perl
ia permisisons permissions
ia perserivn preserving
ia perviw preview
ia phouysical physical
ia physicall physical
ia plaftrom platform
ia plititcal political
ia poeple people
ia poman podman
ia populationof population of
ia porgrams programs
ia possinle possible
ia potrayed portrayed
ia pracitices practices
ia precisson precision
ia prefreneces preferences
ia premisions permissions
ia presentaiton presentation
ia presonal personal
ia prespective prospective
ia prevenet prevent
ia prevfer prefer
ia previeous previous
ia previewous preious
ia previleged privileged
ia prhase phrase
ia pritn print
ia privacey privacy
ia priveous previous
ia proceded proceeded
ia procject project
ia proctechted protected
ia proctechted protected
ia prophtets prophets
ia prophtets prophets
ia propietary proprietary
ia propionents proponents
ia proprietayr proprietary
ia propterties properties
ia prots ports
ia proviate private
ia prtray portray
ia pruposes purposes
ia ptorayed portrayed
ia purgint purging
ia puropose purpose
ia purpos purpose
ia quiestion question
ia quran Qur'an
ia radion radio
ia randonm random
ia randonm random
ia rangkng rangking
ia reature feature
ia recongnize recognize
ia redhat Redhat
ia referrs refers
ia reguar regular
ia relevatn relevant
ia relfect reflect
ia religiouse religious
ia religirons religions
ia reltaed related
ia remvoe remove
ia renadah rendah
ia renadh rendah
ia renmae rename
ia repl real
ia repo rep
ia requried required
ia resasons reasons
ia resons reasons
ia retirun return
ia reveald revealed
ia rithtful rightful
ia rmeove remove
ia rmy my
ia ro or
ia rooot root
ia runing running
ia runique unique
ia saha saja
ia sape shape
ia sarawak Sarawak
ia saty say
ia savely safely
ia sbang #!/bin/sh
ia sbeds beds
ia screeen screen
ia scren screen
ia scrigpt script
ia scultpture sculptures
ia scutlures cultures
ia searhc search
ia sebagh sabah
ia secur recur
ia seee see
ia seeek seek
ia seeral several
ia seeseorang seseorang
ia sentury century
ia sepecies species
ia september September
ia sequenncd sequenced
ia serndir sendiri
ia sesua sesuai
ia setptember september
ia shart start
ia she She
ia shes she's
ia shoudl should
ia shouldnt shouldn't
ia shouled should
ia showereing showering
ia showr show
ia si is
ia si is
ia sice since
ia significat significant
ia signinficance significance
ia signinficantly significantly
ia simultaenously simultaneously
ia sinagaproe Singapore
ia skilstak skilstak
ia slightliy slightly
ia socets sockets
ia soekarno Soekarno
ia soekarno Sukarno
ia soem some
ia softare software
ia softerwere software
ia softwrae software
ia sohuth south
ia somethign something
ia sometines sometimes
ia sometines sometimes
ia somtehing something
ia sould should
ia sourcde sourced
ia sovereingty sovereignty
ia specifed specified
ia specifidc specific
ia specivic specific
ia spedning spending
ia spirirual spiritual
ia sstem system
ia stablished established
ia starbucks Starbucks
ia starndard standard
ia staticaly statically
ia statred started
ia sthe the
ia stil still
ia stonesa stones
ia strenth strength
ia struff stuff
ia suati suatu
ia suc such
ia succesor successor
ia sucdh such
ia suer user
ia sukarno Sukarno
ia surender surrender
ia surprigisng surprising
ia suse use
ia sustioner sustainer
ia swt SWT
ia symbos symbol
ia sytyle style
ia taht that
ia taiwan Taiwan
ia tcp TCP
ia teahidng teaching
ia televisio televisi
ia televisio television
ia teminal terminal
ia temporayr temporary
ia termianal terminal
ia termianl terminal
ia terminall terminal
ia terml terms
ia termnal terminal
ia tesla Tesla
ia tghe the
ia th the
ia tha that
ia thatn than
ia thats that's
ia thean than
ia theat that
ia theem them
ia thefaces the faces
ia theis this
ia theoir their
ia ther their
ia theree there
ia theres there's
ia theres there's
ia theri their
ia therme there
ia thery there
ia thes this
ia thesse these
ia they They
ia theyre they're
ia thie the
ia thieeory theory
ia thiems times
ia thies this
ia thight tight
ia thingk think
ia thinnk think
ia thorugh through
ia thoug though
ia thout thought
ia throught thought
ia tht that
ia thwo two
ia tiem time
ia tierminal terminal
ia tiktok TikTok
ia tithub GitHub
ia tls TLS
ia tomato 🍅
ia tonw town
ia tow two
ia tracet traced
ia tradision tradition
ia traditioally traditionally
ia trasdidiotnal traditional
ia tty TTY
ia tu too
ia tui TUI
ia tursn turn
ia typicalyy typically
ia ubuntu Ubuntu
ia ubuntu Ubuntu
ia ubutnu Ubuntu
ia udp UDP
ia umverella umbrella
ia uncacceptable unacceptable
ia undet under
ia unitued united
ia unix Unix
ia unix Unix
ia unndouubtedly undoubtedly
ia untik untuk
ia unveilled unveiled
ia unversally universally
ia unwnted unwanted
ia upt up
ia usb USB
ia usefull useful
ia useing using
ia userd used
ia usign using
ia usin using
ia usses uses
ia ussuallly usually
ia usualy usually
ia utilitye utility
ia variaous various
ia verison version
ia versiaon version
ia versino version
ia viatal vital
ia vim Vim
ia virtula virtual
ia virtulan virtual
ia vish fish
ia vitual virtual
ia vitual virtula
ia voacab vocab
ia vscode VSCode
ia vuitlin builtin
ia warnign warning
ia warnign warning
ia wasiting wasting
ia wat3er water
ia watchign watching
ia watning wanting
ia watre water
ia wcho echo
ia weeki week
ia wehic which
ia wel well
ia were we're
ia were we're
ia were we're
ia wetern western
ia whar what
ia whats what's
ia whay why
ia whch which
ia whdy why
ia whenn when
ia wher where
ia whidh which
ia whn when
ia whoch which
ia whree where
ia wht what
ia widonws windows
ia wigthin within
ia wiht with
ia wil will
ia windos windows
ia os OS
ia wonderyng wondering
ia wont won't
ia woudl would
ia wouldnt wouldn't
ia writiing writing
ia writting writing
ia wsl WSL
ia wsl2 WSL2
ia wy why
ia wya way
ia wysiwyg what you see is what you get
ia xinjiang Xinjinag
ia yagn yang
ia yare year
ia yello yellow
ia you You
ia youll you'll
ia youre you're
ia yours your's
ia youtube YouTube
ia youu you
ia yu you
ia changeing changing
ia asigned assigned
ia fime time
ia numver number
ia begining beginning
ia osi OSI
ia seccure secure
ia travelt travel
ia negitiaate negotiate
ia dibilanng dibilang
ia nevariously nefariously
ia hoook hook
ia inboun inbound
ia serviece service
ia gelongs belongs
ia nam name
ia pid PID
ia conflic conflict
ia avter after
ia everyting everything
ia trafic traffic
ia paht path
ia preverable preferable
ia wasnt wasn't
ia sepace space
ia rever refer
ia underlaying underlying
ia crete create
ia moistoure moisture
ia prominetn prominent
ia languae language
ia intepreter interpreter
ia permisson permission
ia injedctedd injected
ia binayr binary
ia exteremely extremely
ia prefereed preferred
ia maachine machine
ia handel Handel
ia cooding coding
ia chatch catch
ia intractive interactive
ia wha what
ia posix POSIX
ia liscences licenses
ia gplv3 GPLv3
ia gplv2 GPLv2
ia gpl GPL
ia yoru your
ia hakers hackers
ia linse lines
ia apreciated appreciated
ia complicance compliance
ia emost most
ia dpends depends
ia las last
ia thier their
ia ansd and
ia specidfic specific
ia grpe grep
ia dul 2>/dev/null
ia emebeded embedded
ia swiss Swiss
ia basichs basics
ia littel little
ia hust just
ia lern learn
ia publik public
ia githyub GitHub
ia lcoaly locally
ia chnages changes
ia git Git
ia amenalbe amenable
ia ot to
ia aer are
ia bashic basic
ia sepecifiecally specifically
ia procedurla procedural
ia porgramming programming
ia languange language
ia soudns sounds
ia retirn return
ia avariables variables
ia commnets comments
ia happends happens
ia sixze size
ia paneds panes
ia dleimiters delimiters
ia promram program
ia sufficinet sufficient
ia environmet environment
ia whsy why
ia sequentiallly sequentially
ia parametes parameters
ia singel single
ia ontly only
ia tehe the
ia categorrized categorized
ia varibales variables
ia googel google
ia slugggish sluggish
ia affectionaly affectionaly
ia zealand Zealand
