ca bd bd!
ca epo e /home/dandi/.config/nvim/lua/dandi/abbrev/typos.lua
ca fdin find
ca fidn find
ca lazy Lazy
ca lsit list
ca lspinfo Lspinfo
ca man Man
ca mason Mason
ca n norm
ca q q!
ca t term
ia !! #!/bin/sh
ia @ dandiyuan@proton.me
ia Crearte Create
ia Differecne Difference
ia Doesnt doesn't
ia Everythins Everything
ia Globbing Globing
ia Hwo How
ia Opern Open
ia SOURCEs SOURCES
ia Somethig Something
ia Uncerstatnd Understand
ia Understatnd Understand
ia abobve above
ia abou about
ia acces access
ia accesibility accessibility
ia accetntuate accentuate
ia accetp accept
ia accidently accidentally
ia accomodat accommodate
ia accoutn account
ia accros across
ia acdounts accounts
ia acess acess
ia acpi ACPI
ia acrual actual
ia actualy actually
ia adadnya adanya
ia adala adalah
ia addr3ess address
ia addres address
ia adeueduct aqueduct
ia adfantages advantages
ia administor administer
ia adn and
ia adnroid android
ia adress address
ia advantagge advantage
ia ae are
ia aempty empty
ia aer are
ia affectionaly affectionaly
ia aftern after
ia agge age
ia aggresively aggressively
ia agian again
ia ahd add
ia ahs has
ia aht that
ia ai I
ia ake take
ia aksk ask
ia aliasses aliases
ia allah Allah
ia allah Allah SWT
ia alliaxe Allliance
ia alll all
ia allwah Allah
ia alnalyze analyze
ia alocate allocate
ia aloso also
ia alse also
ia altoogether altogether
ia alwasy always
ia alwsys always
ia amaka maka
ia amattresses mattresses
ia amenalbe amenable
ia america America
ia amil mail
ia amon among
ia amreicans Americans
ia amtrix matrix
ia anceient ancient
ia andn and
ia android Android
ia ane and
ia anoteher another
ia anothere another
ia anoying annoying
ia ansd and
ia answre answer
ia antio nation
ia anythign anything
ia anyting anything
ia anywhre anywhere
ia aournd around
ia apache Apache
ia apaplication application
ia apend append
ia apera appear
ia aperthei apartheid
ia aply apply
ia apperantly apparently
ia apperars appears
ia applicatoin application
ia apreciated appreciated
ia aprop prop
ia apsp apps
ia ar are
ia arabic Arabic
ia archeology archaeology
ia archieve achieve
ia arent aren't
ia areound around
ia arethmatic arithmetic
ia arguent argument
ia argumant argument
ia argumetn argument
ia argumets arguments
ia aristotles Aristotle's
ia aroud around
ia aroung around
ia arros arrows
ia arsterisk asterisk
ia articel article
ia ascii ASCII
ia asean ASEAN 
ia ashemed ashamed
ia asigned assigned
ia asmaller smaller
ia assyra Assyria
ia assyria Assyria
ia ataou atau
ia atchitecture architecture
ia attribure attribute
ia attriubute attribute
ia atuo atau
ia australia Australia
ia automaticaly automatically
ia autoryti authority
ia aututst august
ia availabel available
ia avariables variables
ia avim Vim
ia avodi avoid
ia avter after
ia awater water
ia ayre are
ia bacany bacanya
ia bacanya bapanya
ia backgroudn background
ia backto back to
ia badnwith bandwidth
ia bahea bahwa
ia bandwith bandwidth
ia bashic basic
ia basichs basics
ia bationg bathing
ia batt4ery battery
ia becasue because
ia bechmarking benchmarking
ia becoem become
ia beegitu begitu
ia befor before
ia begginer beginner
ia begginsers beginners
ia beginer beginner
ia beginers beginners
ia begining beginning
ia beigin begin
ia beiing being
ia beleiefes belief's
ia belive believe
ia benefeits benefits
ia beradasarkan berdasarkan
ia berkutat berkarat
ia berperngaruh berpengaruh
ia beter better
ia betwee between
ia betweeen between
ia betwoeen between
ia beyon beyond
ia bi be
ia bidies bodies
ia binari binary
ia binayr binary
ia blaack black
ia blinnk blink
ia bnen been
ia bolld bold
ia borneo Borneo
ia brancd brand
ia breezeless breeze less
ia breifly briefly
ia breitish British
ia briatain Britain
ia british British
ia brittel brittle
ia broser browser
ia brougth brought
ia bruinei Brunei
ia bsd BSD
ia buddhism Buddhism
ia builign building
ia builtins builtin
ia buitlin builtin
ia bulding building
ia bweteen between
ia calcultor calculator
ia cannonical canonical
ia cant can't
ia caoused caused
ia capitaal capital
ia carret caret
ia carrieage carriage
ia catanya caranya
ia categorrized categorized
ia catt call
ia centrury century
ia chabne change
ia chage change
ia chagen change
ia chagne change
ia chagne change
ia changeing changing
ia charachter character
ia characther character
ia chareacter character
ia chatch catch
ia chatgpt ChatGPT
ia cheebkbond cheekbone
ia china China
ia chinas China
ia chinas China's
ia chinese Chinese
ia chnage change
ia chnages changes
ia chnanged changed
ia chooisng choosing
ia chooose choose
ia cintainer container
ia citty city
ia civiliation civilization
ia ckey key
ia classcified classified
ia cleaniess cleanness
ia cleansliness cleanliness
ia clebber clobber
ia cli CLI
ia cliking clicking
ia clipboeard clipboard
ia cna can
ia cnn CNN
ia cntain contain
ia cntainer container
ia cofnlict conflict
ia collectiono collection
ia columnd column
ia comamnd command
ia comand command
ia commadn command
ia comman command
ia commbination combination
ia commersial commercial
ia commited committed
ia commnad command
ia commnand command
ia commnd command
ia commnet comment
ia commnets comments
ia communincation communication
ia companty company
ia compasion compassion
ia compatibel compatible
ia complicance compliance
ia compnay company
ia componnet component
ia comprimising compromising
ia comproisign comprising
ia compteiiton competition
ia computre computer
ia comunicates communicates
ia comunity community
ia comunna communal
ia comuputer computer
ia conatain contain
ia conatainer container
ia concepth concept
ia concurency concurrency
ia condcept concept
ia conde code
ia conditinoal conditional
ia conecrion connection
ia conetent content
ia confert convert
ia confgiure configure
ia configruraation configuration
ia configurain configuration
ia confilict conflict
ia conflic conflict
ia conformace conformance
ia conformant conform ant
ia congainers containers
ia connedctoin connection
ia conrairner container
ia conrect connect
ia consciousnewss consciousness
ia consciouts conscious
ia consideresd considered
ia consita consist
ia consitent consistent
ia consoel console
ia consortioum consortium
ia constartints constraints
ia consumates consummates
ia containder container
ia containerfs containers
ia containner container
ia containts contains
ia contemporrary contemporary
ia contetn content
ia continers containers
ia continoue continue
ia contnent content
ia contol control
ia cooding coding
ia cookeis cookies
ia coomand command
ia cooose choose
ia copmuter computer
ia costco Costco
ia cotnrol control
ia couldnt could't
ia coulnt count
ia countrey country
ia couse cause
ia cpacity capacity
ia cpu CPU
ia creaet create
ia createor creator
ia creationof creation of
ia crestes creates
ia crete create
ia css CSS
ia csv CSV
ia culter culture
ia cummand command
ia currenty currently
ia curucial crucial
ia custoamizatios customization
ia custoers customers
ia custormer customer
ia cutlere culture
ia dangef danger
ia darkmde darkmode
ia de the
ia decenmber December
ia decieded decided
ia declaraation declaration
ia declareed declared
ia decodde decode
ia deevlopers developers
ia defautl default
ia deffault default
ia defived derived
ia dekstop desktop
ia delcared declared
ia delimit4r delimiter
ia delimitery delimiters
ia delte delete
ia democaracy democracy
ia democraicees democracies
ia denagan dengan
ia dependedn depended
ia descentants descendants
ia descriibe describe
ia descripttive descriptive
ia descrptor descriptor
ia detais detail
ia determina determine
ia devault default
ia develeopment development
ia developd developed
ia developmen development
ia dhcp DHCP
ia dibilanng dibilang
ia didnt didn't
ia diea idea
ia diference difference
ia differece difference
ia differecne difference
ia differenche difference
ia differencitates differentiates
ia differents different
ia differnt different
ia difficutl difficult
ia diguui digurui
ia dikalim diklaim
ia dimasksud dimaksud
ia dinnder dinner
ia diplay display
ia dipslaying displaying
ia dipute depute
ia direactory directory
ia direcory directory
ia direcotry directory
ia direcrory directory
ia direcrtory directory
ia directoru Directory
ia directory Directory
ia directoryies directories
ia directoyr directory
ia directy directly
ia directyly directly
ia disj disc
ia dissapeear disappear
ia distictive distinctive
ia distor distro
ia distrubution distribution
ia ditergarai diperbarui
ia divverent different
ia djacent adjacent
ia dleimiters delimiters
ia dns DNS
ia documetary documentary
ia documnet document
ia doesnt doesn't
ia dont don't
ia dosplay display
ia dpeak speak
ia dpends depends
ia dring drink
ia driveing driving
ia dsign design
ia dta data
ia dtatbases databases
ia ducth duct
ia dul 2>/dev/null
ia dut due
ia duthch dutch
ia dvice device
ia dw3m w3m
ia dwonlaod download
ia dwonload download
ia earlisest earliest
ia earss ears
ia easeier easier
ia easyly easily
ia eb be
ia ecleoses encloses
ia ecncoded encoded
ia ecoh echo
ia ecossystem ecosystem
ia edesigned designed
ia edifference difference
ia ediging editing
ia ediotr editor
ia editign editing
ia editro editor
ia editror editor
ia efect effect
ia effecgt effect
ia effetctiev effective
ia ehave have
ia eho who
ia eht the
ia eill will
ia electoronic electronic
ia elemnt element
ia elemnts elements
ia eliptical elliptical
ia emacs Emacs
ia emebeded embedded
ia emost most
ia emphaise emphasis
ia emulateor emulator
ia enalble enable
ia encapsulete encapsulate
ia ener enter
ia english English
ia enterprize enterprise
ia entrie entire
ia env ENV
ia envireonment environment
ia environmen environment
ia environmet environment
ia envv Environment Variables
ia epalace palace
ia eps EPS
ia equivlents equivalents
ia escapt escape
ia escreen screen
ia esitimator estimator
ia espanssions expansions
ia eth the
ia ethernet Ethernet
ia eurasia Eurasia
ia europ Europe
ia euser user
ia eveery every
ia eveerywhere everywhere
ia evefry every
ia evertyhong everything
ia everyting everything
ia excelent excellent
ia excetp except
ia exchagne exchagne
ia exchagne exchange
ia exchgen exchange
ia executbale executable
ia exif EXIF
ia exixting existing
ia exmple example
ia expansoion expansion
ia experieced experienced
ia expresion expression
ia expresssions expressions
ia exteremely extremely
ia fafourige favorite
ia fainth faith
ia falue value
ia falues values
ia federationf federation
ia femoved removed
ia feture future
ia ffom from
ia fideo video
ia fidn find
ia fiedl field
ia fiel fail
ia fiel file
ia fiels files
ia fielsd fields
ia fierwalls firewalls
ia filell file ll
ia filnally finally
ia filse files
ia filsystem filesystem
ia filterign filtering
ia fim vim
ia fime time
ia finallly finally
ia finaly finally
ia finnish finish
ia firest first
ia firewalll firewall
ia firtual virtual
ia fle file
ia flie file
ia fo of
ia folloiwng following
ia formater formater
ia fornt front
ia fromat format
ia frou from
ia fucntion function
ia funcamgental fundamental
ia funcrion function
ia functiono function
ia furdamentals fundamentals
ia furnitrue furniture
ia fwiw for what it's worth
ia gabe gave
ia gactory factory
ia gelongs belongs
ia generaly generally
ia generatio generation
ia genra genera
ia genvironment environment
ia gerbawah terbawah
ia gerp grep
ia ghath that
ia ghe the
ia gihtyb GitHub
ia git Git
ia github GitHub
ia githyub GitHub
ia glboal global
ia gloabaly globally
ia gloave glove
ia globa global
ia globbla global
ia globla global
ia gnerator generator
ia gnome GNOME
ia gnu GNU
ia goies goes
ia golang Golang
ia googd good
ia googel google
ia goto go-to
ia governorate governor ate
ia gpl GPL
ia gplv2 GPLv2
ia gplv3 GPLv3
ia gpu GPU
ia graphicl graphical
ia greek Greek
ia greeks Greeks
ia groeup group
ia groudn ground
ia grousp group
ia grpe grep
ia grumpt grumpy
ia gruping grouping
ia gta Grand Theft Auto
ia gui GUI
ia guis GUIs
ia gutorial tutorial
ia gutys guys
ia hakers hackers
ia hallowoin hallowing
ia handel Handel
ia hans hand
ia happends happens
ia happesns happens
ia hased hashed
ia hatumu hatimu
ia hdr ####################################################################
ia hdup hidup
ia he He
ia headign heading
ia hello Hello
ia helo Hello
ia helpd help
ia heres here's
ia herval herbal
ia hes he's
ia hhousehold household
ia hhow how
ia hiddenf hidden
ia hieararchy hierarchy
ia hifher higher
ia hightlight highlight
ia hiliy hilir
ia hinduism Hinduism
ia hinga hingga
ia hins hints
ia hisotians historians
ia hisotry history
ia histor history
ia hlep help
ia hoem home
ia hong Hong
ia hoook hook
ia houdeholds households
ia houese house
ia houman human
ia how How
ia hree here
ia hsared shared
ia htahun tahun
ia htan than
ia htat that
ia hte the
ia htis this
ia hundresds hundreds
ia hust just
ia hwat what
ia hwatis whatis
ia hwo how
ia hwy why
ia hygine hygiene
ia i I
ia iach each
ia iam I am
ia iamages images
ia iamge image
ia icmp ICMP
ia id ID 
ia identitty identity
ia idesa ideas
ia idnetical identical
ia idnonesia Indonesia
ia ifferent different
ia ifles files
ia ifnormatin information
ia iformation formation
ia iinstall install
ia iirc IIRC
ia iircc if I remember correctly
ia iis is
ia im I'm
ia imags image
ia imamah Imamah
ia imge image
ia immams imams
ia imortance importance
ia impertaive imperative
ia impies implies
ia implict implicit
ia impolementation implementation
ia impolies implies
ia imporoved improved
ia imporovements improvements
ia importan important
ia importatn important
ia improev improve
ia inadvertnet inadvertent
ia inavetebly inevitably
ia inboun inbound
ia incetpion inception
ia includde include
ia includin including
ia incoporation incorporation
ia independdecne independence
ia independece independence
ia indesks indeks
ia indifidual individual
ia indo Indonesia
ia indoeneasia Indonesia
ia indoenesian Indonesian
ia indoensia Indonesia
ia indoensians Indonesians
ia indoesias Indonesia's
ia indonesia Indonesia
ia indonesian Indonesian
ia indonesians Indonesians
ia indonesias Indonesia
ia indtation indentation
ia ineteesting interesting
ia infiite infinite
ia informatinfor information for
ia informatino information
ia infuential influential
ia ingle single
ia ingnore ignore
ia ingormation information
ia inidonesians Indonesians
ia injedctedd injected
ia inodonesia Indonesia
ia inoed inode
ia inoformation information
ia inot into
ia inovasinya inovasi nya
ia insatall install
ia inshell in shell
ia inslay inlay
ia insonesia Indonesia
ia instaead instead
ia instalation installation
ia installaiton installation
ia institued instituted
ia insuficient insufficient
ia intepreter interpreter
ia interacet interact
ia interal internal
ia interenet internet
ia intergraition integration
ia intermitten intermittent
ia intermpereter interpreter
ia intermpretation interpretation
ia intet intent
ia intractive interactive
ia introductiono introduction
ia introuduce introduce
ia intsalation installation
ia involfe involve
ia invormation information
ia ip IP
ia ipp IPP
ia ipv4 IPv4
ia ipv6 IPv6
ia islam Islam
ia isn in
ia isnt isn't
ia isze size
ia it It
ia iterm2 iTerm2
ia itesm items
ia itll it'll
ia itmean it mean
ia itn in
ia itno into
ia its it's
ia iwdely widely
ia iwll will
ia jakarta Jakarta
ia jaopanese Japanese
ia japan Japan
ia japanaese Japanese
ia japanese Japanese
ia japanesee Japanese
ia japn japan
ia javascript JavaScript
ia jesus Jesus
ia jkt Jakarta
ia josb jobs
ia jpeg JPEG
ia js JavaScript
ia json JSON
ia judaism Judaism
ia jungel jungle
ia kapitanya kapita nya
ia kebuuthan kebutuhan
ia kerashya kerasnya
ia kindl kindle
ia kisd kids
ia knowledgte knowledge
ia knwon known
ia kong Kong
ia kusage usage
ia lan LAN
ia languae language
ia languange language
ia lanjupt lanjut
ia largaer larger
ia las last
ia latesst latest
ia launchhed launched
ia lcoaly locally
ia lein line
ia lengthh length
ia lern learn
ia lettter letter
ia levarage leverage
ia levell level
ia liead lead
ia liek like
ia lightwieght lightweight
ia lik link
ia lin line
ia linee line
ia lineked linked
ia ling link
ia linivng lining
ia linkt link
ia linse lines
ia linux Linux
ia linxu Linux
ia liscences licenses
ia lishcense license
ia liteasi literasi
ia literasin literasi
ia litreasinya literasinnya
ia littel little
ia litteraly literally
ia locla local
ia logica logic
ia loook look
ia lornum exec curl -sSL "http://metaphorpsum.com/paragraphs/"<left>
ia lsit list
ia lsitens listens
ia lua Lua
ia lup for i in {1..}; do echo item $i.; done<esc>?}<cr>i
ia lvies lives
ia lwas law
ia maachine machine
ia maanager manager
ia machhine machine
ia machien machine
ia maek make
ia magter matter
ia maintaenance maintenance
ia maket make
ia malacca Malacca
ia malasyia Malaysia
ia malaya Malaya
ia malayisia Malaysia
ia malaysia Malaysia
ia malaysuia Malaysia
ia manaage manage
ia manaeger manager
ia manageement management
ia manchines machines
ia manger manager
ia manke make
ia markdonw Markdown
ia markdown Markdown
ia markdwon markdown
ia marksers markers
ia masyarakay masyarakat
ia matchies matches
ia materialzied materialized
ia mattial martial
ia maximumm maximum
ia md5 MD5
ia meata meta
ia mee Dandi Yuan Aridianto
ia meiji Meiji
ia memeofry memory
ia memeorabel memorable
ia memeorh memory
ia memgbers members
ia memilikii memiliki
ia mengadapi menghadapi
ia mengakiibatkan mengakibatkan
ia mengaktakan mengatakan
ia mentri menteri
ia messanger messenger
ia mexican Mexican
ia mgh https://github.com/Yuandandi
ia microsoft Microsoft
ia midified modified
ia milions millions
ia minght might
ia misstype mistype
ia moderyn modern
ia modivy modify
ia moistoure moisture
ia moniotor monitor
ia monitr monitor
ia mor more
ia morining morning
ia mornign morning
ia moses Moses
ia moset most
ia motorcyle motorcycle
ia moveing moving
ia movile mobile
ia mozilla Mozilla
ia mroe more
ia mtatter matter
ia muhamad Muhammad
ia muhamma Muhammad
ia muhammads Muhammad's
ia multinationa multinational
ia multipel multiple
ia muroid muroid
ia muschles muscles
ia musilim Muslim
ia muslim Muslim
ia muslims Muslims
ia mux tmux
ia nad and
ia nam name
ia namd named
ia namesa names
ia nat NAT
ia natrual natural
ia navbigate navigate
ia naviagation navigation
ia nebara negara
ia necessayr necessary
ia nections sections
ia ned need
ia negar negara
ia negitiaate negotiate
ia neovim NeoVim
ia netehrelands Netherlands
ia neter enter
ia netework network
ia netflix Netflix
ia netherlands Netherlands
ia nethernlands Netherlands
ia netive native
ia networkign networking
ia nevariously nefariously
ia newlinen newline
ia newwer newer
ia nmpa nmap
ia noah Noah
ia nodieis bodies
ia noew new
ia nokia Nokia
ia nokiaas Nokia's
ia nokias Nokia's
ia nost most
ia notgherlands Netherlands
ia noth north
ia nothig nothing
ia nothign nothing
ia nott not
ia ntetwork network
ia nto not
ia nubmer number
ia nuemerical numerical
ia nuerous numerous
ia numer number
ia numericc numeric
ia numver number
ia numverical numerical
ia nwme name
ia obbsessed obsessed
ia obvsessed obsessed
ia ocassionaly occasionally
ia occuiped occupied
ia occuraces occur aces
ia occureances occurrences
ia occurence occurrence
ia occurences occurrences
ia ocmmand command
ia ocntiue continue
ia ocpy copy
ia ocur occur
ia od do
ia oera era
ia oetstat netstat
ia ofer over
ia ofirgins origins
ia ofr for
ia ofrmat format
ia ofthen often
ia ofther other
ia ogher other
ia ogten often
ia ohowever however
ia ohw how
ia ois is
ia oit It
ia okey okay
ia omg OMG
ia omited omitted
ia onet one
ia onlhy only
ia ont not
ia ont on
ia ontly only
ia onwe one
ia oone one
ia openeing opening
ia openssh OpenSSH
ia oper open
ia operatin operation
ia opernsource ope resource
ia optinal optional
ia optioin option
ia optionla optional
ia oraganization organization
ia origis origin
ia os OS
ia osi OSI
ia ot to
ia otehr other
ia oter other
ia oter otter
ia otgher other
ia othe other
ia otomatisa otomatis
ia otpions options
ia otu out
ia ouptut output
ia ov of
ia overlaped overlapped
ia ownd own
ia p_elemnet p_element
ia packges packages
ia padnoc pandoc
ia paht path
ia pakcages packages
ia paneds panes
ia papaer paper
ia parametere parameters
ia parametes parameters
ia parrent parent
ia particualr particular
ia pbuh PBUH
ia pdf PDF
ia peacefullly peacefully
ia pembershian pembersihan
ia peninsuallar peninsular
ia penuat penguat
ia peower power
ia perforamance performance
ia performang performing
ia peritn print
ia perku perlu
ia perl Perl
ia permisisons permissions
ia permisson permission
ia permorming performing
ia pernickety persnickety
ia perserivn preserving
ia perviw preview
ia phouysical physical
ia physicall physical
ia pid PID
ia pirnt print
ia pitfals pitfalls
ia plaftrom platform
ia playabel playable
ia plititcal political
ia png PNG
ia poeple people
ia poman podman
ia populationof population of
ia porcesses processes
ia porgramming programming
ia porgrams programs
ia porne prone
ia posix POSIX
ia possinle possible
ia potrayed portrayed
ia pracitices practices
ia preciding preceding
ia precisson precision
ia prefereed preferred
ia prefious previous
ia prefreneces preferences
ia preinted printed
ia preious previous
ia premisions permissions
ia preocedures procedures
ia preoceedure procedure
ia prepetrator perpetrator
ia presentaiton presentation
ia presonal personal
ia prespective prospective
ia prevenet prevent
ia preverable preferable
ia prevfer prefer
ia previdous previous
ia previeous previous
ia previewous preious
ia previleged privileged
ia prevneting preventing
ia prhase phrase
ia priciples principles
ia prin preen
ia pring print
ia pritn print
ia privacey privacy
ia priveous previous
ia proceded proceeded
ia procedre procedure
ia procedurla procedural
ia proceudure procedure
ia procject project
ia proctechted protected
ia profide provide
ia profirt profit
ia progaming programming
ia programing programming
ia prominetn prominent
ia promram program
ia promtp prompt
ia properti property
ia prophtets prophets
ia propietary proprietary
ia propionents proponents
ia proprietayr proprietary
ia propterties properties
ia prormat format
ia prot port
ia prots ports
ia proviate private
ia prtray portray
ia pruposes purposes
ia pseed speed
ia ptogram program
ia ptorayed portrayed
ia publik public
ia purgint purging
ia puropose purpose
ia purpos purpose
ia qr QR
ia questeion question
ia quiestion question
ia quiotes quotes
ia quran Qur'an
ia radion radio
ia randonm random
ia rangkng rangking
ia readlink read link
ia reature feature
ia recongnize recognize
ia recuresively recursively
ia recuresvely recursively
ia recurevel recuresively
ia recurseive recursive
ia redhat Redhat
ia redirectign redirecting
ia redner render
ia referrs refers
ia reguar regular
ia reidirect redirect
ia relevatn relevant
ia relfect reflect
ia religiouse religious
ia religirons religions
ia reltaed related
ia removeing removing
ia remve remove
ia remvoe remove
ia remvoed removed
ia renadah rendah
ia renadh rendah
ia rendre render
ia renmae rename
ia repl real
ia repo rep
ia repositroy repository
ia requried required
ia requriemetns requirements
ia resasons reasons
ia resons reasons
ia resutl result
ia retirn return
ia retirun return
ia retturn return
ia reveald revealed
ia rever refer
ia rithtful rightful
ia rmeove remove
ia rmy my
ia ro or
ia rooot root
ia runing running
ia runique unique
ia saha saja
ia sape shape
ia sarawak Sarawak
ia saty say
ia savely safely
ia sbeds beds
ia scatered scattered
ia scipt sci pt
ia screeen screen
ia scren screen
ia scrigpt script
ia scrpt script
ia scultpture sculptures
ia scutlures cultures
ia searchsploti searchsploit 
ia searhc search
ia sebagh sabah
ia seccure secure
ia secrue secure
ia secur recur
ia secureity security
ia seee see
ia seeek seek
ia seeral several
ia seeseorang seseorang
ia semanics semantics
ia sensiteive sensitive
ia sentury century
ia seo SEO
ia sepace space
ia sepecies species
ia sepecifiecally specifically
ia september September
ia sequenncd sequenced
ia sequentiallly sequentially
ia serndir sendiri
ia serviece service
ia sesua sesuai
ia setptember september
ia shart start
ia she She
ia shes she's
ia shoppign shopping
ia shor show
ia shoudl should
ia shoulc should
ia shouldnt shouldn't
ia shouled should
ia showereing showering
ia showr show
ia shuch such
ia si is
ia sice since
ia siet site
ia significat significant
ia signinficance significance
ia signinficantly significantly
ia siletn silent
ia simillar similar
ia simultaenously simultaneously
ia sinagaproe Singapore
ia singel single
ia sixze size
ia skilstak skilstak
ia slightliy slightly
ia slugggish sluggish
ia socets sockets
ia soekarno Soekarno
ia soekarno Sukarno
ia soem some
ia softare software
ia softerwere software
ia softweare software
ia softwrae software
ia sohuth south
ia somehting something
ia somethign something
ia sometines sometimes
ia somtehing something
ia soources sources
ia soudns sounds
ia sould should
ia sourcde sourced
ia sovereingty sovereignty
ia speciall special
ia speciallity specialty
ia specidfic specific
ia specifed specified
ia specifes specifies
ia specifidc specific
ia specivic specific
ia spedning spending
ia spirirual spiritual
ia splititng splitting
ia sstem system
ia stablished established
ia stagging staging
ia standadr standard
ia starbucks Starbucks
ia starndard standard
ia stateement statement
ia staticaly statically
ia statred started
ia steatlh stealth
ia sthe the
ia stil still
ia stonesa stones
ia strenth strength
ia struff stuff
ia sttus status
ia suati suatu
ia subtitution substitution
ia subtitutions substitutions
ia suc such
ia succesfully successfully
ia succesfuly successfully
ia succesor successor
ia sucdh such
ia suer user
ia sufficinet sufficient
ia sufix suffix
ia sukarno Sukarno
ia suppresed suppressed
ia surender surrender
ia suroundign surrounding
ia surprigisng surprising
ia suse use
ia sustioner sustainer
ia swhitch switch
ia swiss Swiss
ia swt SWT
ia sybmolic symbolic
ia symbolci symbols
ia symbos symbol
ia syntak syntax
ia sytyle style
ia taht that
ia taiwan Taiwan
ia takign taking
ia taks taks
ia tcp TCP
ia teahidng teaching
ia teh the
ia tehe the
ia televisio televisi
ia televisio television
ia teminal terminal
ia temporayr temporary
ia termianal terminal
ia termianl terminal
ia terminall terminal
ia terml terms
ia termnal terminal
ia tesla Tesla
ia tghe the
ia th the
ia tha that
ia thatn than
ia thats that's
ia thean than
ia theat that
ia theem them
ia theer there
ia thefaces the faces
ia theis this
ia theoir their
ia ther their
ia theree there
ia theres there's
ia theri their
ia therme there
ia thery there
ia thes this
ia thesse these
ia thext text
ia they They
ia theyre they're
ia thie the
ia thieeory theory
ia thiems times
ia thier their
ia thies this
ia thight tight
ia thign thing
ia thigns things
ia thingk think
ia thinnk think
ia thorugh through
ia thoruth through
ia thoug though
ia thout thought
ia throug through
ia throught thought
ia tht that
ia thwo two
ia tiem time
ia tierminal terminal
ia tiktok TikTok
ia tithub GitHub
ia tlah telah
ia tls TLS
ia todah today
ia todo TODO
ia togetheh together
ia tomato 🍅
ia tonw town
ia tow two
ia tracet traced
ia tradision tradition
ia traditioally traditionally
ia trafic traffic
ia trasdidiotnal traditional
ia travelt travel
ia treu true
ia tty TTY
ia tu too
ia tui TUI
ia tursn turn
ia typicalyy typically
ia ubuntu Ubuntu
ia ubutnu Ubuntu
ia udner under
ia udnoubtedly undoubtedly
ia udp UDP
ia uisngg using
ia umverella umbrella
ia uncacceptable unacceptable
ia underlaying underlying
ia underpinings underpinnings
ia undershore underscore
ia undet under
ia uniquie unique
ia unitued united
ia unix Unix
ia unladden unladen
ia unndouubtedly undoubtedly
ia unsuccesfully unsuccessfully
ia untik untuk
ia unveilled unveiled
ia unversally universally
ia unwnted unwanted
ia uphil uphill
ia upt up
ia url URL
ia urls URLs
ia usb USB
ia usefull useful
ia useing using
ia usenames usernames
ia userd used
ia usign using
ia usin using
ia using Using
ia usng using
ia usptream upstream
ia usses uses
ia ussuallly usually
ia usualy usually
ia utilitky utility
ia utilitye utility
ia utitility utility
ia valu vale
ia variabel variable
ia variaous various
ia varibales variables
ia veing being
ia veiw view
ia verifid verified
ia verison version
ia versiaon version
ia versino version
ia version version
ia viatal vital
ia viddeo video
ia videous video's
ia viles files
ia vim Vim
ia virtua virtual
ia virtula virtual
ia virtulan virtual
ia vish fish
ia vitual virtual
ia vitual virtula
ia voacab vocab
ia vscode VSCode
ia vuitlin builtin
ia waht What
ia warnign warning
ia wasiting wasting
ia wasnt wasn't
ia wat3er water
ia watchign watching
ia watning wanting
ia watre water
ia wcho echo
ia weeki week
ia wehic which
ia wel well
ia were we're
ia wetern western
ia wha what
ia whar what
ia what What
ia whats what's
ia whay why
ia whch which
ia whdy why
ia when When
ia whenn when
ia wher where
ia whidh which
ia whn when
ia whoch which
ia whree where
ia whsy why
ia wht what
ia wi whatis
ia widnows windows
ia widonws windows
ia wigthin within
ia wiht with
ia wil will
ia windos windows
ia wiritten written
ia withoiut without
ia woerk work
ia wokr work
ia wonce once
ia wonderyng wondering
ia wont won't
ia woudl would
ia wouldnt wouldn't
ia writiing writing
ia writting writing
ia wsl WSL
ia wsl2 WSL2
ia wy why
ia wya way
ia wysiwyg what you see is what you get
ia xinjiang Xinjinag
ia xslt XSLT
ia yagn yang
ia yare year
ia yello yellow
ia yoou you
ia yoru your
ia you You
ia youll you'll
ia youre you're
ia yours your's
ia yousing using
ia youtube YouTube
ia youu you
ia yu you
ia gihtub GitHub
ia withing within
ia zealand Zealand
